# Site settings
title: "Tom Ossowski, Director, Music Director"
email: tom@tomossowski.com
description: > # this means to ignore newlines until "baseurl:"
  Tom Ossowski is a stage director and music director. He
  teaches in the BFA Music Theatre Program at 
  Florida State University, is the Producing Artistic Director 
  for the Post Playhouse at Fort Robinson State Park in 
  Nebraska, and is on the faculty at The Central Academy of Drama 
  in Beijing, China.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://happycollision.github.io" # the base hostname & protocol for your site

# Build settings
markdown: redcarpet
redcarpet:
  extensions: ['smart']

permalink: pretty

exclude:
  - .bowerrc
  - .gitignore
  - bower.json

prose:
  siteurl: 'http://happycollision.github.io/jekyll.tomossowski.com/'
  media: 'media'
  metadata:
    _posts:
      - name: "layout"
        field:
          element: "hidden"
          value: "post"
      - name: "title"
        field:
          element: "text"
          label: "Title"
          value: ""
      # - name: "splash"
      #   field:
      #     element: "text"
      #     label: "Splash image"
      #     value: ""
    # _posts/static:
    #   - name: "layout"
    #     field:
    #       element: "hidden"
    #       value: "page"
    #   - name: "title"
    #     field:
    #       element: "text"
    #       label: "Title"
    #       value: ""
    #   - name: "permalink"
    #     field:
    #       element: "text"
    #       label: "Permalink"
    #       value: ""
